design first commit
mariammnamgaladze/SpaceChatApp pull request #1
Opened 2023-04-16 11:29 UTC by mariammnamgaladze

design first commit

2023-04-17 10:48 UTC, iTarley commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="6dp"
ყველგან სადაც სტატიკურად გიწერია dp და sp უნდა გაიტანო ცალკე res/values/dimension.xml

2023-04-17 10:57 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_second.xml
> +        android:layout_height="0dp"
გამომრჩა რამდენიმე ადგილას 😂 ბოლოს შევქმენი dimen-ების ფაილი

2023-04-17 10:58 UTC, mariammnamgaladze commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="6dp"
აქაც გამომრჩა 😄

2023-04-17 10:58 UTC, mariammnamgaladze commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="0dp"
აქაც გამომრჩა 😄

2023-04-17 10:58 UTC, mariammnamgaladze commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="0dp"
აქაც გამომრჩა 😄

2023-04-17 10:59 UTC, mariammnamgaladze commented on app/src/main/res/navigation/nav_graph.xml
nav_graph-ის შექმნისას თვითონ შემომთავაზა დამატება ისე არ იტვირთებოდა

2023-04-17 13:27 UTC, Gio481 requested changes

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/java/com/example/spacechatapp/presentation/first_screen/FirstFragment.kt
> +class FirstFragment : BaseFragment<FragmentFirstBinding>(FragmentFirstBinding::inflate) {
მე არ მომწონს first და second ფრაგმენტები შეგიძლია zezva mzia დაარქვა ან top bottom, შესაბამისად ვიუმოდელებსაც და ფოლდერის სახელებიც, ფოლდერის სახელებზე მაგალითად სახელი_screen არ გინდა, პირდაპირ სახელი

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/drawable/custom_input.xml
> +        </shape>
100დპ და 2დპ რესურსებში

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/drawable/sms_background.xml
> +    <corners android:radius="25dp" />
ესეც რესურსებში

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_first.xml
> +        android:id="@+id/firstFrRV"
აიდებსაც ფრაგმენტებს რო გადაარქმევ შესაბამისად გადაარქვი

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_first.xml
> +        app:layout_constraintHorizontal_bias="1.0"
bias ატრიბუტი წასაშლელია

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_first.xml
> +        android:layout_height="@dimen/et_height"
ზომებს შესაბამისი ზომების სახელები გადაარქვი

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_first.xml
> +        android:layout_marginEnd="@dimen/dimen_16dp"
marginHorizontal

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_first.xml
> +        android:ems="10"
ems:10 რას ნიშნავს თუ არ გჭირდება წაუშალე

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_second.xml
> +        android:id="@+id/smsEditText2"
2 არ უნდა ბოლოში :დ რომელი სქრინზეცაა ეს აიდი მაგ სქრინის სახელით დაიწყე აიდიც და ერთნაიერები აღარ გექნება და სადაც ასე გაქვს ყველაგან გადააკეთე

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_second.xml
> +        android:layout_marginEnd="@dimen/dimen_16dp"
marginHorizontal

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_second.xml
> +        android:id="@+id/imageButton9"
მოკლედ, აიდების სახელები გაქ შესაცვლელი 😃

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/from.xml
> +    android:layout_marginEnd="@dimen/dimen_120dp">
120dp ით რატო აშორებ, ფიგმაში თუ ნახე ასე, მაშინ ფიგმაში რო ერთი სიტყვა ყოფილიყო იმის ზომას ხო არ დააშორებდი, დაუპატარავე ზომა

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/from.xml
> +        android:layout_width="10dp"
რესურსებიში :დ

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/from.xml
> +        android:textSize="@dimen/date_txt_size"
date_txt_size არა, რა თუ 14სპ მაშინ dimen_14sp

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/to.xml
> +    android:layout_marginStart="@dimen/dimen_120dp"
აქაც იგივე, არმგონია ამხელა დაშორება ლამაზი იყოს

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/navigation/nav_graph.xml
როგორ არ იტვირთებოდა ისე ?

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/values-night/themes.xml
>      <style name="Theme.SpaceChatApp" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
ამაზე არ აკეთებ noActionBar ?

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/from.xml
from და to სახელები არა, შეგიძლია send__sms_layout_item, receive_sms_layout_item ან რაიმე მსგავსი

2023-04-17 13:27 UTC, Gio481 commented on app/src/main/res/layout/from.xml
> +        android:textSize="@dimen/sms_txt_size"
დაამატე სტილები სადაც გექნება მაგალითად, smallMyriadGeo_Normal, mediumMyriadGeo_Bold, და ასე შემდეგ და სტილებში გექნება ტექსტის ზომა, ფერი და ფონტი, და ყველა ტექსტვიუზე და ედითტექესზე ამ სტილებს გამოიყენებ, თუ მაგალითად სმალში 12 სპ გაქ ტესქსტი და გინდა რო 10 ქონდეს ჩვეულებრივ სტილსაც გაუწერ და ტესქტის ზომასაც იმ კონკრეტულს ტექსტვიუში

2023-04-17 16:39 UTC, iTarley commented on app/src/main/java/com/example/spacechatapp/presentation/first_screen/FirstFragment.kt
> +class FirstFragment : BaseFragment<FragmentFirstBinding>(FragmentFirstBinding::inflate) {
Top/bottom არც ისე კარგი სახელებია, იმიტომ რომ Landscape support უნდა იყოს

2023-04-18 06:46 UTC, Gio481 commented on app/src/main/java/com/example/spacechatapp/presentation/first_screen/FirstFragment.kt
> +class FirstFragment : BaseFragment<FragmentFirstBinding>(FragmentFirstBinding::inflate) {
ზეზვა მზია მაშინ :დ first second რაღაცა ცუდია რა 😃

2023-04-18 07:18 UTC, mariammnamgaladze commented on app/src/main/res/navigation/nav_graph.xml
არ ვიცი, არ ჩაიტვირთა

2023-04-18 07:21 UTC, mariammnamgaladze commented on app/src/main/res/values-night/themes.xml
>      <style name="Theme.SpaceChatApp" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
გამომრჩა 😄

2023-04-18 09:31 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/first_screen/FirstFragment.kt
> +class FirstFragment : BaseFragment<FragmentFirstBinding>(FragmentFirstBinding::inflate) {
@mariammnamgaladze  ზეზვა და მზია არ დაარქვა არაა სწორი :D მაგაზე მომხვდა თავისდროზე :D

2023-04-18 09:34 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/MainActivity.kt
> +            .add(binding.secondFragment.id, SecondFragment())
ეცადე რო ერთ ფრაგმენტით წახვიდე ორივე იუზერისთვის

2023-04-18 10:16 UTC, gioqemoklidze requested changes

2023-04-18 10:16 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +        return binding.root
if (_binding == null) {
            _binding = bindingInflater(inflater, container, false)
        }
დაგაზღვევს თუ ბაინდინგს მნიშვენლობა მინიჭებულიაქ მეორედ აღარ მიენიჭება

2023-04-18 10:40 UTC, gioqemoklidze commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="0dp"
0dp ს დიმენშენებში გატანა სავლდებულო არაა 0დპ ყველგნ 0 დპა ამ დიმენშენებში გატანის  მუღამი ისაარომ შეგიძლია სხვადასხვა გაფართოების ეკრანისთვისთვის შექმნა დიმენშენ ფაილები და dimen_5dp სიტყვაზე პატარა ეკრანზე იყოს 5დპ დიდზე კიდე 7დპ

2023-04-18 12:42 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +        return binding.root
სორი ის ვერ შევამჩნიე ბაინდინგს ონდესტროი ვიუში რომ ანალებ როცა ეგ გიწერია მაშინ ეს ჩეკი აღარაა საჭირო იმიტორო ონდესტროიში ყველავარიანტში განალდება ბაინდინგი და ეს ქეისი არ დაგიდგება

2023-04-18 12:44 UTC, GiorgiMamagulashvil1 commented
just advice, split commits by their purpose, this action will help you to manage your branch, also  set relevant name of commit and title of  pull request  by content ))

2023-04-18 13:06 UTC, bchmsl requested changes

2023-04-18 13:06 UTC, bchmsl commented on app/src/main/res/layout/from.xml
> +        android:id="@+id/smsTV"
ზოგგან EditText-ით მთავრდება აიდი, ზოგგან TV-თი
ან TV / ET -ით დაარქვი, ან TextView / EditText

2023-04-18 13:06 UTC, bchmsl commented on app/src/main/res/layout/to.xml
> +        android:id="@+id/dotIv"
აქაც აიდზე Iv ქვია, სხვაგან ზოგგან IV, ზოგგან ImageView

2023-04-18 13:06 UTC, bchmsl commented on app/src/main/res/layout/fragment_second.xml
> +    <EditText
ზოგგან AppCompat გაქვს გამოყენებული, ზოგგან ჩვეულებრივი. ეცადე ერთნაირი ელემენტები გამოიყენო

2023-04-18 13:06 UTC, bchmsl commented on app/src/main/res/values/colors.xml
> +    <color name="dark_background">#160039</color>
ფერს ფერის სახელი დაარქვი, სჯობს, ამ შემთხვევაში "dark_blue" ან რაიმე მსგავსი

2023-04-18 13:06 UTC, bchmsl commented on app/src/main/res/values/dimens.xml
> +    <dimen name="date_txt_size">11sp</dimen>
სახელებიი

2023-04-18 13:06 UTC, bchmsl commented on app/src/main/res/values/dimens.xml
> +    <dimen name="et_height">56dp</dimen>
სახელებიიიიიი

2023-04-18 17:35 UTC, bchmsl commented on app/src/main/res/values/strings.xml
>      <string name="hello_blank_fragment">Hello blank fragment</string>
არ გჭირდება

2023-04-18 17:35 UTC, bchmsl commented on app/src/main/res/values/strings.xml
>      <string name="input_hint">something...</string>
დიზაინში რაცაა მოცემული ის ტექსტი ჩასვი

2023-04-18 17:37 UTC, bchmsl commented on app/src/main/res/values/styles.xml
> +    </style>
სტილებს მშობლები გაუწერე რომ ნებისმიერ ელემენტზე არ შეგეძლოს სტილად დამატება

2023-04-18 17:40 UTC, bchmsl commented on app/src/main/res/drawable/custom_input.xml
ამ სელექტორის აითემებს შორის რა განსხვავებაა ან ეს სელექტორი რისთვისაა?

2023-04-18 17:41 UTC, bchmsl commented on app/src/main/res/layout/fragment_bottom.xml
> +        app:hintEnabled="false"
hintEnabled სტილში ისედაც გაქვს გაწერილი

2023-04-18 17:42 UTC, bchmsl commented on app/src/main/res/layout/fragment_bottom.xml
> +            android:paddingEnd="@dimen/dimen_30dp"
paddingEnd-იც სტილში გაიტანე

2023-04-18 17:43 UTC, bchmsl commented on app/src/main/res/layout/fragment_bottom.xml
id-ების გაწერის დროს არაა საჭირო დააკონკრეტო topFragment-ია თუ bottomFragment, რადგან სხვადასხვა xml ფაილებში გიწერია და binding-ს იყენებ. უბრალოდ დააწერე sendBtn და ა.შ ორივე ფრაგმენტზე

2023-04-18 17:45 UTC, bchmsl commented on app/src/main/res/layout/fragment_top.xml
აიდების შესახებ რაც fragment_bottom.xml-ში დაგიწერე იგივე

2023-04-19 08:17 UTC, Gio481 commented on app/src/main/res/layout/fragment_bottom.xml
> +            android:paddingEnd="@dimen/dimen_30dp"
არა, არ უნდა იყოს პედინგები და მარჯინები სტილებში

2023-04-19 09:52 UTC, Gio481 approved these changes

2023-04-19 13:12 UTC, iTarley commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +        _binding = this.inflate().invoke(inflater, container, false)
if (_binding == null) {
            _binding = this.inflate().invoke(inflater, container, false)
        } 
ეგრე ხოლმე შეგიძლია დაწერო, ამ დროს უეჭველი იცი რომ მართო ერთი binding ცოცხლობს

2023-04-19 13:12 UTC, iTarley commented on app/src/main/res/layout/activity_main.xml
> +            />
იგივე რაც ზევით დაგიწერე, უფრო მარტივია ერთი იმაგე-ბუტონი ან საერთოდ სვიჩი რომ იყოს

2023-04-19 13:13 UTC, iTarley commented on app/src/main/res/layout-land/activity_main.xml
> +
ისე რა კარგად მოვნიშნე ხაზები :დ

2023-04-20 07:41 UTC, AnaRusadze requested changes
1. gitignore ფაილში  მიამატე ".idea/" რომ პრში ამ გაფართოებების ფაილები არ გამოჩნდეს
2. სურათებს შეეცადე რომ ყოველთვის თან რამე პრეფიქსი ჰქონდეს, მაგალითად ic_ როცა აიქონია, bkg_ როცა ბექგრაუნდია
3. კოდი დააფორმატირე ხოლმე სულ
4. dimen ზრდადობის მიხედვით დაალაგე, რომ სუფთად ეწეროს
5. შეგიძლია შენც სცადო send და receive ლეიაუთების გაერთიანება და ერთი ვიუს გამოყენება ორივე შემთხვევაში. დაგეხმარება  პროგრამულად ფერის და scaleX ის შეცვლა

2023-04-20 08:28 UTC, mariammnamgaladze commented on app/src/main/res/drawable/custom_input.xml
agar vikeneb amas washla damaviwkda

2023-04-20 08:30 UTC, mariammnamgaladze commented on app/src/main/res/values/dimens.xml
ar mereva isedac hahah :D

2023-04-20 10:06 UTC, mariammnamgaladze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(private val inflater: Inflater<VB>) : Fragment() {
done

2023-04-20 10:06 UTC, mariammnamgaladze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +    abstract fun start()
done

2023-04-20 10:06 UTC, mariammnamgaladze commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="0dp"
done

2023-04-20 10:06 UTC, mariammnamgaladze commented on app/src/main/java/com/example/spacechatapp/presentation/first_screen/FirstFragment.kt
> +class FirstFragment : BaseFragment<FragmentFirstBinding>(FragmentFirstBinding::inflate) {
done

2023-04-20 10:06 UTC, mariammnamgaladze commented on app/src/main/res/drawable/custom_input.xml
> +        </shape>
done

2023-04-20 10:06 UTC, mariammnamgaladze commented on app/src/main/res/drawable/sms_background.xml
> +    <corners android:radius="25dp" />
done

2023-04-20 10:06 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_first.xml
> +        android:id="@+id/firstFrRV"
done

2023-04-20 10:07 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_first.xml
> +        app:layout_constraintHorizontal_bias="1.0"
done

2023-04-20 10:07 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_first.xml
> +        android:layout_height="@dimen/et_height"
done

2023-04-20 10:07 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_first.xml
> +        android:ems="10"
done

2023-04-20 10:07 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_first.xml
> +        tools:ignore="TextContrastCheck,TextContrastCheck" />
done

2023-04-20 10:07 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_first.xml
> +        android:id="@+id/imageButton2"
done

2023-04-20 10:07 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_second.xml
> +        android:id="@+id/smsEditText2"
done

2023-04-20 10:07 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_second.xml
> +        android:layout_marginEnd="@dimen/dimen_16dp"
done

2023-04-20 10:08 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_second.xml
> +        android:id="@+id/imageButton9"
done

2023-04-20 10:08 UTC, mariammnamgaladze commented on app/src/main/res/values-night/themes.xml
>      <style name="Theme.SpaceChatApp" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
done

2023-04-20 10:08 UTC, mariammnamgaladze commented on app/src/main/res/layout/from.xml
done

2023-04-20 10:08 UTC, mariammnamgaladze commented on app/src/main/res/layout/from.xml
> +        android:textSize="@dimen/sms_txt_size"
done

2023-04-20 10:08 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_first.xml
> +        android:id="@+id/firstFrRV"
done

2023-04-20 10:09 UTC, mariammnamgaladze commented on app/src/main/res/layout/from.xml
> +        android:id="@+id/smsTV"
done

2023-04-20 10:09 UTC, mariammnamgaladze commented on app/src/main/res/layout/to.xml
> +        android:id="@+id/dotIv"
done

2023-04-20 10:09 UTC, mariammnamgaladze commented on app/src/main/java/com/example/spacechatapp/presentation/MainActivity.kt
>              .commit()
done

2023-04-20 10:10 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_bottom.xml
> +            style="@style/Base.Widget.MaterialComponents.TextInputEditText.MessageTextInputEditText"            android:layout_width="match_parent"
done

2023-04-20 10:10 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_top.xml
> +            style="@style/Base.Widget.MaterialComponents.TextInputEditText.MessageTextInputEditText"            android:layout_width="match_parent"
done

2023-04-20 10:10 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_bottom.xml
> +        app:hintEnabled="false"
done

2023-04-20 10:10 UTC, mariammnamgaladze commented on app/src/main/java/com/example/spacechatapp/presentation/MainActivity.kt
> +    }
done

2023-04-20 10:10 UTC, mariammnamgaladze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +    protected val binding get() = _binding
done

2023-04-20 10:10 UTC, mariammnamgaladze commented on app/src/main/res/layout/activity_main.xml
> +            />
done

2023-04-20 10:11 UTC, mariammnamgaladze commented on app/src/main/res/navigation/nav_graph.xml
done

2023-04-20 10:25 UTC, gioqemoklidze requested changes

2023-04-20 10:25 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/bottom/BottomFragment.kt
> +    private val viewModel: BottomFragmentViewModel by viewModels()
ვიუმოდელის ამოღება ბეიზში გაიტანე და მერე ონბაინდს გამოატანე პარამეტრად

2023-04-20 10:40 UTC, bchmsl commented on app/src/main/res/values/dimens.xml
კაი ჩემო ძმაო, გავითვალისწინებ

2023-04-20 10:45 UTC, bchmsl approved these changes
აიდებთან დაკავშირებით რაღაც ხარვეზები ისევ არის 🥲

2023-04-20 10:49 UTC, mariammnamgaladze commented on app/src/main/java/com/example/spacechatapp/presentation/bottom/BottomFragment.kt
> +    private val viewModel: BottomFragmentViewModel by viewModels()
done

2023-04-20 10:55 UTC, gioqemoklidze requested changes

2023-04-20 10:55 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +    protected abstract val viewModel: VM
ეს ვიუმოდელ კლასი ფრაივათი გახადე  ცალკე ცვლადი ან ფუნქცია შექმენი რომელიც ვიუმოდელის კლასს ამოიღებს და მერე ონქრიეითში getViewModel ით ამოიღე ეგ ვიუმოდელი ,ახლა ეს რაც გიწერია უბრალოდ იმას აკეთებს რო ქცევას უწესებ ყველა შვილობილს რო ვიუმოდელი უნდა გქონდეს

2023-04-20 11:32 UTC, AnaRusadze requested changes

2023-04-20 11:32 UTC, AnaRusadze commented on app/src/main/res/layout/receive_sms_layout_item.xml
> +    android:layout_marginEnd="@dimen/dimen_120dp">
მარჯინ ენდი დინამიურია და სქრინის მიხედვით შეიცვლება. შეეცადე რომ სტატიკური მარჯინები მხოლოდ იმ მხრიდან დაუწერო, რასთანაც ახლოს არის ვიუ და დიდი რიცხვები არ გამოიყენო

2023-04-20 11:32 UTC, AnaRusadze commented on app/src/main/res/layout/send__sms_layout_item.xml
> +    android:layout_marginStart="@dimen/dimen_120dp"
იგივე აქაც

2023-04-20 14:12 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +    protected abstract val viewModel: VM
di ს როცა დაამატებ მაშინ გააკეთე

2023-04-20 14:14 UTC, gioqemoklidze approved these changes

2023-04-20 14:14 UTC, mariammnamgaladze commented on app/src/main/res/layout/receive_sms_layout_item.xml
> +    android:layout_marginEnd="@dimen/dimen_120dp">
done

2023-04-20 14:15 UTC, mariammnamgaladze commented on app/src/main/res/layout/send__sms_layout_item.xml
> +    android:layout_marginStart="@dimen/dimen_120dp"
done

2023-04-20 14:16 UTC, AnaRusadze approved these changes

2023-04-20 14:23 UTC, merged